### ISSUE TITLE
svg-icon

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/svg-icon.js#4]
### Development

- [x]  Ability to use `folder/icon-name` or simply `icon-name` as a value in the `name` attribute.
    - [x] #11
- [x]  Convert `name` to a Slot. Basically `<svg-icon>icon-name</svg-icon>`
- [x]  `svg-icon.config.js` for
    - [x]  Locating the Icons' folder when in use.
    - [x]  Defining a global default size.
    - [x]  Defining a global default color.
    - [x] Defining a global default icon name.
- [x] #13
- [x] #7
- [x] #12

### Design

- [x]  readme.md
- [x]  Make the codebase Whitelabel and mark the "placeholders" for organizations to fill.
- [x]  Create a simple and stupid landing page
- [x]  HN / Twitter / dev.to

**Comment by talent0411** [comment]
Fixed the above 6 items.

Now need to work on icons.html, icons.js

Can you provide task specs for them?

**Comment by talent0411** [comment]
@edenvidal 
I've completed icons.html and icons.js.
